### ISSUE TITLE
Errors in tests after forking

### ISSUE THREAD

**Issue by jasonjunweilyu** [hiker/fab#4]
After forking from the original repo, currently errors are reported when running both the system and unit tests. Specifically, the tests failed are:

**I. System tests**:

================================= short test summary info =================================
FAILED system_tests/psyclone/test_psyclone.py::TestPsyclone::test_run - RuntimeError: Command failed with return code 1:
FAILED system_tests/psyclone/test_psyclone.py::TestPsyclone::test_prebuild - RuntimeError: Command failed with return code 1:
========================= 2 failed, 41 passed, 42 warnings in 70.59s (0:01:10) ========================

**II. Unit tests**:

All unit tests passed when `pytest tests/unit_tests` from the fab folder.

**III. Running all tests**:

When `pytest tests` from the fab folder, there is a collecting error:
===================================== ERRORS =====================================
_________________________________ ERROR collecting tests/unit_tests/steps/grab/test_svn_fcm.py ________________________________
import file mismatch:
imported module 'test_svn_fcm' has this `__file__` attribute:
  tests/system_tests/svn_fcm/test_svn_fcm.py
which is not the same as the test file we want to collect:
  tests/unit_tests/steps/grab/test_svn_fcm.py
HINT: remove `__pycache__` / .pyc files and/or use a unique basename for your test file modules
=============================== short test summary info ================================
ERROR tests/unit_tests/steps/grab/test_svn_fcm.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================== 1 error in 2.65s ==================================

**Comment by hiker** [comment]
Fixed with #9 , closing this issue now.
